### ISSUE TITLE
can't recreate the scene

### ISSUE THREAD

**Issue by AfifSoussi** [AgoraIO-Community/Unity-Virtual-Camera-Prefab#2]
HI great job on this it's exactly what i was looking for,
one problem though, the scene you're using is missing from the files, is it possible to share the whole project ?

or at least what objects should i create for those ?
    private GameObject RemoteVideoRoot;
    private GameObject RemoteScreenVideoRoot;

thanks a lot !

**Comment by zhangtao1104** [comment]
@digitallysavvy You need to upload the .meta file。

**Comment by digitallysavvy** [comment]
@AfifSoussi I've written a [guide](https://www.agora.io/en/blog/how-to-build-a-vr-video-chat-app-using-unitys-xr-framework/) on how to implement this plugin as part of a VR scene. 

I’ll make note to add a demo scene in the next update.

**Comment by skymeson** [comment]
A demo scene would be great. I have not been able to get this working even after following the guide.

**Comment by icywind** [comment]
Please see [this repo](https://github.com/AgoraIO-Community/UnityVirtualCamDemos) for demos of using the prefab.  Note the demos are simplified enough to show the usage, and it is not the same demo that was mentioned in blog above.
