### ISSUE TITLE
Remote video is just white. 

### ISSUE THREAD

**Issue by skymeson** [AgoraIO-Community/Unity-Virtual-Camera-Prefab#3]
When I join from a second computer, I see the RemoteVideoRoot is populated, however the video is blank. The material is instanced and has no texture assigned. Perhaps I did not set up the project correctly?

**Comment by icywind** [comment]
Yep. It is very easy to get this wrong. But don't worry, we have [a new set of simple demos ](https://github.com/AgoraIO-Community/UnityVirtualCamDemos) to show the usage. Please check it out.
